Proje Final Atos/Models/DataContext.cs
using Microsoft.EntityFrameworkCore;

namespace Proje_Final_Atos.Models
{
    public class DataContext:DbContext
    {
        public DataContext(DbContextOptions<DataContext>options):base(options)
        {

        }
        public DbSet <Livro> livros { get; set; }
    }
}

Proje Final Atos/Models/ErrorViewModel.cs
namespace Proje_Final_Atos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Proje Final Atos/Models/Livro.cs
using System.ComponentModel.DataAnnotations;

namespace Proje_Final_Atos.Models
{
    public class Livro
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Informe o Titulo do Livro")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "Informe o SubTitulo do Livro")]
        public string SubTitulo { get; set; }
        [Required(ErrorMessage = "Informe o Autor do Livro")]
        public string Autor { get; set; }
        [Required(ErrorMessage = "Informe o Genero do Livro")]
        public string Genero { get; set; }
        [Required(ErrorMessage = "Informe o Idioma do Livro")]
        public string Idioma { get; set; }
        [Required(ErrorMessage = "Informe a Capa do Livro")]
        public string Capa { get; set; }
        [Required(ErrorMessage = "Informe a Resenha do Livro")]
        public string Resenha { get; set; }
    }
}

Proje Final Atos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Proje_Final_Atos.Models;
using System.Diagnostics;

namespace Proje_Final_Atos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Proje Final Atos/Controllers/LivroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proje_Final_Atos.Models;

namespace Proje_Final_Atos.Controllers
{
    public class LivroesController : Controller
    {
        private readonly DataContext _context;

        public LivroesController(DataContext context)
        {
            _context = context;
        }

        // GET: Livroes
        public async Task<IActionResult> Index()
        {
              return View(await _context.livros.ToListAsync());
        }

        // GET: Livroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.livros == null)
            {
                return NotFound();
            }

            var livro = await _context.livros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // GET: Livroes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Livroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,SubTitulo,Autor,Genero,Idioma,Capa,Resenha")] Livro livro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(livro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.livros == null)
            {
                return NotFound();
            }

            var livro = await _context.livros.FindAsync(id);
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        // POST: Livroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,SubTitulo,Autor,Genero,Idioma,Capa,Resenha")] Livro livro)
        {
            if (id != livro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.livros == null)
            {
                return NotFound();
            }

            var livro = await _context.livros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.livros == null)
            {
                return Problem("Entity set 'DataContext.livros'  is null.");
            }
            var livro = await _context.livros.FindAsync(id);
            if (livro != null)
            {
                _context.livros.Remove(livro);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(int id)
        {
          return _context.livros.Any(e => e.Id == id);
        }
    }
}

Proje Final Atos/Controllers/PersonagensController.cs
using Microsoft.AspNetCore.Mvc;

namespace Proje_Final_Atos.Controllers
{
    public class PersonagensController : Controller
    {
        public IActionResult Hermione()
        {
            return View();
        }

        public IActionResult Gandalf()
        {
            return View();
        }


        public IActionResult Aelin()
        {
            return View();
        }
    }
}

Proje Final Atos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div id="myCarousel" class="carousel slide border border-dark shadow-sm p-1 mb-1 bg-gradient" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>

    </ol>
    <div class="carousel-inner">


        <div class="carousel-item active carousel-item-left">
            <img class="third-slide" src="~/css/Walker-Scobell-Percy-Jackson.png" alt="Third slide">
            <div class="container">
                <div class="carousel-caption text-right">
                    <h1>Adapção de Livros</h1>
                    <p>TV E SÉRIES Walker Scobell é Percy Jackson na nova série do Disney+!</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Saiba Mais</a></p>
                </div>
            </div>
        </div>
    </div>

</div>
<br />
<br />
<br />
<div class="text-white bg-gradient">
   
    <h1 class=" text-white">Recomendações da Semana</h1>
</div>
<div class="container">

   
    <div class="row text-white fs-5">
        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-1 mb-1 bg-gradient">
            <div class="card">
                <img class="card-img-top " src="~/css/capa harry potter.jpg" alt="Imagem de capa do card">
            </div>
            <div class="card-body">
                <h5 class="card-title">Harry Potter e a Pedra Filosofal</h5>
                <p Class="card-text">“Harry Potter e a Pedra Filosofal é o primeiro dos sete livros da série de fantasia Harry Potter, escrita por J. K. Rowling. O livro conta a história de Harry Potter, um órfão criado pelos tios que descobre, em seu décimo primeiro aniversário, que é um bruxo.”</p>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-1 mb-1 bg-gradient">
            <div class="card">
                <img class="card-img-top" src="~/css/os seis finalistas.jpg" alt="Imagem de capa do card">
            </div>
            <div class="card-body">
                <h5 class="card-title">Os Seis Finalistas</h5>
                <p Class="card-text">“A Missão Especial mais audaciosa da história é lançada: a colonização de Europa, uma das luas de Júpiter. ..”</p>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-1 mb-1 bg-gradient">
            <div class="card">
                <img class="card-img-top" src="~/css/caraval.jpg" alt="Imagem de capa do card">
            </div>
            <div class="card-body">
                <h5 class="card-title">Caraval</h5>
                <p Class="card-text">““O que quer que tenha ouvido sobre o Caraval não se compara a realidade. É mais do que só um jogo ou apresentação. É a coisa mais parecida com magia que você verá neste mundo.””</p>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-1 mb-1 bg-gradient">
            <div class="card">
                <img class="card-img-top" src="~/css/Codigo_Limpo-scaled.jpg" alt="Imagem de capa do card">
            </div>
            <div class="card-body">
                <h5 class="card-title">Habilidades práticas do Agile Software</h5>
                <p Class="card-text">“Mesmo um código ruim pode funcionar. Mas se ele não for limpo, pode acabar com uma empresa de desenvolvimento. Perdem-se a cada ano horas incontáveis e recursos importantes devido a um código mal escrito. Mas não precisa ser assim.O renomado especialista em software, Robert C. Martin, apresenta um paradigma revolucionário com Código limpo: Habilidades Práticas do Agile Software. ”</p>
            </div>
        </div>


        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-1 mb-1 bg-gradient">
            <div class="card">
                <img class="card-img-top" src="~/css/padroes.jpg" alt="Imagem de capa do card">
            </div>
            <div class="card-body">
                <h5 class="card-title">Habilidades práticas do Agile Software</h5>
                <p Class="card-text">“Catálogo de soluções simples e sucintas para os problemas mais freqüentes na área de projeto, assinado por quatro profissionais com grande experiência em software orientado a objetos. Um best-seller mundial. ”</p>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-1 mb-1 bg-gradient">
            <div class="card">
                <img class="card-img-top" src="~/css/CodificadorLimpo.jpg" alt="Imagem de capa do card">
            </div>
            <div class="card-body">
                <h5 class="card-title">Um código de conduta para programadores profissionais </h5>
                <p Class="card-text">“O Codificador Limpo contém muitos conselhos pragmáticos que visam transformar o comportamento do profissional de software. O autor transmite valiosos ensinamentos sobre ética, respeito, responsabilidade, sinceridade e comprometimento, através de sua experiência como programador. ”</p>
            </div>
        </div>
    </div>
    <br /><br /><br />
    <div class ="text-white bg-gradient">
    <h1 >Pesornagens</h1>
    </div>
    <br />
</div>
<div class="container opacity-100 fs-5">
    <div class="row text-white ">
        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-2 mb-3 bg-gradient">
            <a class="navbar-brand" asp-area="" asp-controller="Personagens" asp-action="Hermione">
            <div class="card bg-black bg-opacity-50 ">
                <img class="card-img-top rounded-circle" src="~/css/hermione.webp" alt="Imagem de capa do card">
            </div>
            </a>
            <div class="card-body">
                
                <h4 class="card-title">Hermione Granger</h4>
                <a>Hermione é uma garota de personalidade forte. Não se deixa manipular por qualquer coisa, está sempre atenta a qualquer risco. Gosta de pensar antes de agir para que, futuramente, não haja algum prejuízo para ela e seus companheiros atrapalhados. Uma jovem sábia, esperta e persistente.</a>
                
            </div>

        </div>

        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-2 mb-3 bg-gradient ">
             <a class="navbar-brand" asp-area="" asp-controller="Personagens" asp-action="Gandalf">
            <div class="card bg-black bg-opacity-50">
                <img class="card-img-top rounded-circle" src="~/css/gandalf2.jpg" alt="Imagem de capa do card">
            </div>
            </a>
            <div class="card-body">
                <h4 class="card-title">Gandalf</h4>
                <a> Gandalf é um homem sábio e respeitoso. Ele sempre reconforta seus parceiros e é reconhecido por ser uma pessoa calorosa e cheia de amor. Gandalf também é implacável em combate, não respeitando seus inimigos, soltando algumas ofensas e se irritando.</a>
            </div>

        </div>


        <div class="col-12 col-md-6 col-lg-4 border border-dark shadow-sm p-2 mb-3 bg-gradient ">
            <a class="navbar-brand" asp-area="" asp-controller="Personagens" asp-action="Aelin">
            <div class="card bg-black bg-opacity-50">
                <img class="card-img-top rounded-circle" src="~/css/Aelin Galathynius..jpeg" alt="Imagem de capa do card">
            </div>
            </a>
            <div class="card-body">
                <h4 class="card-title ">Aelin Galathynius</h4>
                <a>Aelin Ashryver Galathynius, também conhecida como Celaena Sardothien, é a rainha perdida de Terrasen e o último membro sobrevivente da linhagem Galathynius. </a>
            </div>

        </div>


    </div>
</div>

Proje Final Atos/Views/Livroes/Create.cshtml
@model Proje_Final_Atos.Models.Livro

@{
    ViewData["Title"] = "Create";
}




<hr />

<div class=" border border-dark shadow-sm p-1 mb-1 bg-gradient  ">
    
    <div class="container ">
        <div class="row justify-content-md-center">
            <h1 class="text-white">Adicionar um Novo Livro</h1>
            <div class="col-md-5">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group  text-white">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group  text-white">
                        <label asp-for="SubTitulo" class="control-label"></label>
                        <input asp-for="SubTitulo" class="form-control" />
                        <span asp-validation-for="SubTitulo" class="text-danger"></span>
                    </div>
                    <div class="form-group  text-white">
                        <label asp-for="Autor" class="control-label"></label>
                        <input asp-for="Autor" class="form-control" />
                        <span asp-validation-for="Autor" class="text-danger"></span>
                    </div>
                    <div class="form-group  text-white">
                        <label asp-for="Genero" class="control-label"></label>
                        <input asp-for="Genero" class="form-control" />
                        <span asp-validation-for="Genero" class="text-danger"></span>
                    </div>
                    <div class="form-group  text-white">
                        <label asp-for="Idioma" class="control-label"></label>
                        <input asp-for="Idioma" class="form-control" />
                        <span asp-validation-for="Idioma" class="text-danger"></span>
                    </div>
                    <div class="form-group  text-white">
                        <label asp-for="Capa" class="control-label"></label>
                        <input asp-for="Capa" class="form-control" />
                        <span asp-validation-for="Capa" class="text-danger"></span>
                    </div>
                    <div class="form-group   text-white">
                        <label asp-for="Resenha" class="control-label"></label>
                        <textarea asp-for="Resenha" class="form-control"></textarea>
                        <span asp-validation-for="Resenha" class="text-danger"></span>
                    </div>
                    <p></p>
                    <div class="form-group  text-white ">
                        <input type="submit" value="Adicionar" class="btn btn-success  w-100" />
                    </div>
                </form>
             
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index"><button type="button" class="btn btn-success">Voltar para lista</button> </a>
   
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proje Final Atos/Views/Livroes/Delete.cshtml
@model Proje_Final_Atos.Models.Livro

@{
    ViewData["Title"] = "Delete";
}

<h1 class=" text-white">Deletar</h1>

<h3 class="text-white">Você Realmente Deseja Deletar?</h3>
<div class=" border border-dark shadow-sm p-1 mb-1 bg-gradient">
    <div class="container text-white">
        <div class="row justify-content-md-center">
            <div class="col-md-5">
                <h4>Livro</h4>
                <hr />
                <dl class="row text-white">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Titulo)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Titulo)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SubTitulo)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SubTitulo)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Autor)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Autor)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Genero)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Genero)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Idioma)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Idioma)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Capa)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Capa)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Resenha)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Resenha)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Deletar" class="btn btn-danger" /> |
                    <a asp-action="Index"><button type="button" class="btn btn-success">Voltar para lista</button> </a>
                </form>
            </div>
        </div>
    </div>
</div>

Proje Final Atos/Views/Livroes/Details.cshtml
@model Proje_Final_Atos.Models.Livro

@{
    ViewData["Title"] = "Details";
}



<div class="border border-dark shadow-sm p-1 mb-1 bg-gradient">
    <div class="container text-white">
        <div class="row justify-content-md-center">
            <h1>Details</h1>
            <h4>Livro</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Titulo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Titulo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.SubTitulo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.SubTitulo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Autor)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Autor)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Genero)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Genero)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Idioma)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Idioma)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Capa)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Capa)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Resenha)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Resenha)
                </dd>
            </dl>
        </div>
    </div>
</div>
<div>
    <button type="button" class="btn btn-warning">
        <a class="text-decoration-none text-white" asp-action="Edit" asp-route-id="@Model?.Id">Editar</a>
    </button>|
    <a asp-action="Index"><button type="button" class="btn btn-success">Voltar para lista</button> </a>
</div>

Proje Final Atos/Views/Livroes/Edit.cshtml
@model Proje_Final_Atos.Models.Livro

@{
    ViewData["Title"] = "Edit";
}
<h1 class="text-white">Editar Livro</h1>

<hr />
<div class=" border border-dark shadow-sm p-1 mb-1 bg-gradient  text-white">

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-5">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Titulo" class="control-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SubTitulo" class="control-label"></label>
                        <input asp-for="SubTitulo" class="form-control" />
                        <span asp-validation-for="SubTitulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Autor" class="control-label"></label>
                        <input asp-for="Autor" class="form-control" />
                        <span asp-validation-for="Autor" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Genero" class="control-label"></label>
                        <input asp-for="Genero" class="form-control" />
                        <span asp-validation-for="Genero" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Idioma" class="control-label"></label>
                        <input asp-for="Idioma" class="form-control" />
                        <span asp-validation-for="Idioma" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Capa" class="control-label"></label>
                        <input asp-for="Capa" class="form-control" />
                        <span asp-validation-for="Capa" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Resenha" class="control-label"></label>
                       
                        <textarea asp-for="Resenha" class="form-control" ></textarea>
                        <span asp-validation-for="Resenha" class="text-danger"></span>
                    </div>
                    <p></p>
                    <div class="form-group">
                        <input type="submit" value="Salvar" class="btn btn-success  w-100" />
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<div>
    <a asp-action="Index"><button type="button" class="btn btn-success" >Voltar para lista</button> </a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}